name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install python deps (from pyproject.toml)
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install debian deps
        run: |
          sudo apt-get update
          sudo apt-get install gcc-riscv64-unknown-elf
          sudo apt-get install yosys nextpnr-ecp5

      - name: Build gateware (FPGA bitstream)
        run: |
          echo "TODO: call LiteX build script"
          python hw/build.py --build --integrated-rom-size=0x8000

      - name: Build firmware
        run: |
          #make -C sw/firmware

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iceguard-build
          path: |
            hw/build/
            sw/firmware/build/
          if-no-files-found: ignore
